services:
  redis:
    image: "redis:7"
    container_name: boutique-redis
    ports:
      - "6379:6379"
    networks:
      - boutique-net

  frontend:
    build: ./src/frontend
    container_name: boutique-frontend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING:-}
      - DISABLE_PROFILER=${DISABLE_PROFILER:-}
      - ENABLE_TRACING=${ENABLE_TRACING:-0}
    networks:
      - boutique-net
    depends_on:
      - cartservice
      - productcatalogservice
      - currencyservice
      - recommendationservice
      - shippingservice
      - paymentservice
      - adservice
      - emailservice
      - shoppingassistantservice

  adservice:
    build: ./src/adservice
    container_name: boutique-adservice
    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING:-}
      - DISABLE_PROFILER=${DISABLE_PROFILER:-}
    networks:
      - boutique-net

  cartservice:
    build: ./src/cartservice/src
    container_name: boutique-cartservice
    environment:
      - REDIS_ADDR=redis:6379
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING:-}
    networks:
      - boutique-net
    depends_on:
      - redis

  checkoutservice:
    build: ./src/checkoutservice
    container_name: boutique-checkoutservice
    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING:-}
      - DISABLE_PROFILER=${DISABLE_PROFILER:-}
    networks:
      - boutique-net

  currencyservice:
    build: ./src/currencyservice
    container_name: boutique-currencyservice
    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING:-}
      - DISABLE_PROFILER=${DISABLE_PROFILER:-}
    networks:
      - boutique-net

  emailservice:
    build: ./src/emailservice
    container_name: boutique-emailservice
    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING:-}
      - DISABLE_PROFILER=${DISABLE_PROFILER:-}
    networks:
      - boutique-net

  loadgenerator:
    build: ./src/loadgenerator
    container_name: boutique-loadgenerator
    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING:-}
    networks:
      - boutique-net

  paymentservice:
    build: ./src/paymentservice
    container_name: boutique-paymentservice
    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING:-}
      - DISABLE_PROFILER=${DISABLE_PROFILER:-}
    networks:
      - boutique-net

  productcatalogservice:
    build: ./src/productcatalogservice
    container_name: boutique-productcatalogservice
    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING:-}
      - DISABLE_PROFILER=${DISABLE_PROFILER:-}
    networks:
      - boutique-net

  recommendationservice:
    build: ./src/recommendationservice
    container_name: boutique-recommendationservice
    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING:-}
      - DISABLE_PROFILER=${DISABLE_PROFILER:-}
    networks:
      - boutique-net

  shippingservice:
    build: ./src/shippingservice
    container_name: boutique-shippingservice
    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING:-}
      - DISABLE_PROFILER=${DISABLE_PROFILER:-}
    networks:
      - boutique-net

  shoppingassistantservice:
    build: ./src/shoppingassistantservice
    container_name: boutique-shoppingassistantservice
    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING:-}
    networks:
      - boutique-net

networks:
  boutique-net:
    driver: bridge
