services:
  # Jaeger - Open Source Distributed Tracing
  jaeger:
    image: jaegertracing/all-in-one:1.52
    container_name: boutique-jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Jaeger HTTP collector
      - "14250:14250"  # Jaeger gRPC collector
      - "6831:6831/udp"  # Jaeger agent
      - "6832:6832/udp"  # Jaeger agent
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - boutique-net

  redis:
    image: "redis:7"
    container_name: boutique-redis
    ports:
      - "6379:6379"
    networks:
      - boutique-net

  frontend:
    build: ./src/frontend
    container_name: boutique-frontend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - COLLECTOR_SERVICE_ADDR=jaeger:14250
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - ENABLE_TRACING=${ENABLE_TRACING:-1}
    networks:
      - boutique-net
    depends_on:
      - jaeger
      - cartservice
      - productcatalogservice
      - currencyservice
      - recommendationservice
      - shippingservice
      - paymentservice
      - adservice
      - emailservice
      - shoppingassistantservice

  adservice:
    build: ./src/adservice
    container_name: boutique-adservice
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - jaeger

  cartservice:
    build: ./src/cartservice/src
    container_name: boutique-cartservice
    environment:
      - REDIS_ADDR=redis:6379
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - redis
      - jaeger

  checkoutservice:
    build: ./src/checkoutservice
    container_name: boutique-checkoutservice
    environment:
      - COLLECTOR_SERVICE_ADDR=jaeger:14250
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - jaeger

  currencyservice:
    build: ./src/currencyservice
    container_name: boutique-currencyservice
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - jaeger

  emailservice:
    build: ./src/emailservice
    container_name: boutique-emailservice
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - jaeger

  loadgenerator:
    build: ./src/loadgenerator
    container_name: boutique-loadgenerator
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - jaeger

  paymentservice:
    build: ./src/paymentservice
    container_name: boutique-paymentservice
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - jaeger

  productcatalogservice:
    build: ./src/productcatalogservice
    container_name: boutique-productcatalogservice
    environment:
      - COLLECTOR_SERVICE_ADDR=jaeger:14250
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - jaeger

  recommendationservice:
    build: ./src/recommendationservice
    container_name: boutique-recommendationservice
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - jaeger

  shippingservice:
    build: ./src/shippingservice
    container_name: boutique-shippingservice
    environment:
      - COLLECTOR_SERVICE_ADDR=jaeger:14250
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - jaeger

  shoppingassistantservice:
    build: ./src/shoppingassistantservice
    container_name: boutique-shoppingassistantservice
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - jaeger

networks:
  boutique-net:
    driver: bridge
