services:
  # Jaeger - Open Source Distributed Tracing
  jaeger:
    image: jaegertracing/all-in-one:1.52
    container_name: boutique-jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Jaeger HTTP collector
      - "14250:14250"  # Jaeger gRPC collector
      - "6831:6831/udp"  # Jaeger agent
      - "6832:6832/udp"  # Jaeger agent
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - boutique-net

  redis:
    image: "redis:7"
    container_name: boutique-redis
    ports:
      - "6379:6379"
    networks:
      - boutique-net

  frontend:
    build: ./src/frontend
    container_name: boutique-frontend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - COLLECTOR_SERVICE_ADDR=jaeger:14250
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - ENABLE_TRACING=1
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8080
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
      - EMAIL_SERVICE_ADDR=emailservice:8080
      - SHOPPING_ASSISTANT_SERVICE_ADDR=shoppingassistantservice:8080
      - ENABLE_ASSISTANT=true
    networks:
      - boutique-net
    depends_on:
      - jaeger
      - cartservice
      - productcatalogservice
      - currencyservice
      - recommendationservice
      - shippingservice
      - paymentservice
      - adservice
      - emailservice
      - shoppingassistantservice

  adservice:
    build: ./src/adservice
    container_name: boutique-adservice
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - jaeger

  cartservice:
    build: ./src/cartservice/src
    container_name: boutique-cartservice
    environment:
      - REDIS_ADDR=redis:6379
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - redis
      - jaeger

  checkoutservice:
    build: ./src/checkoutservice
    container_name: boutique-checkoutservice
    environment:
      - COLLECTOR_SERVICE_ADDR=jaeger:14250
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - EMAIL_SERVICE_ADDR=emailservice:8080
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
    networks:
      - boutique-net
    depends_on:
      - jaeger

  currencyservice:
    build: ./src/currencyservice
    container_name: boutique-currencyservice
    environment:
      - PORT=7000
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - jaeger

  emailservice:
    build: ./src/emailservice
    container_name: boutique-emailservice
    environment:
      - PORT=8080
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - jaeger

  loadgenerator:
    build: ./src/loadgenerator
    container_name: boutique-loadgenerator
    environment:
      - FRONTEND_ADDR=frontend:8080
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - jaeger
      - frontend

  paymentservice:
    build: ./src/paymentservice
    container_name: boutique-paymentservice
    environment:
      - PORT=50051
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - jaeger

  productcatalogservice:
    build: ./src/productcatalogservice
    container_name: boutique-productcatalogservice
    environment:
      - PORT=3550
      - COLLECTOR_SERVICE_ADDR=jaeger:14250
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - jaeger

  recommendationservice:
    build: ./src/recommendationservice
    container_name: boutique-recommendationservice
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - jaeger

  shippingservice:
    build: ./src/shippingservice  
    container_name: boutique-shippingservice
    environment:
      - PORT=50051
      - COLLECTOR_SERVICE_ADDR=jaeger:14250
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - jaeger

  # Shopping Assistant Service - Mock implementation for local development
  # Provides AI-like responses without requiring Google Cloud services
  shoppingassistantservice:
    build: 
      context: ./src/shoppingassistantservice
      dockerfile: Dockerfile.mock
    container_name: boutique-shoppingassistantservice
    environment:
      - PORT=8080
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - boutique-net
    depends_on:
      - jaeger

  # NOTE: The original shoppingassistantservice requires Google Cloud services (AlloyDB, Secret Manager, Google AI)
  # For production deployment with full AI capabilities, uncomment and configure below:
  # shoppingassistantservice:
  #   build: ./src/shoppingassistantservice
  #   container_name: boutique-shoppingassistantservice
  #   environment:
  #     - PORT=8080
  #     - PROJECT_ID=your-gcp-project-id
  #     - REGION=your-gcp-region
  #     - ALLOYDB_DATABASE_NAME=your-alloydb-name
  #     - ALLOYDB_TABLE_NAME=your-table-name
  #     - ALLOYDB_CLUSTER_NAME=your-cluster-name
  #     - ALLOYDB_INSTANCE_NAME=your-instance-name
  #     - ALLOYDB_SECRET_NAME=your-secret-name
  #     - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
  #   networks:
  #     - boutique-net
  #   depends_on:
  #     - jaeger

networks:
  boutique-net:
    driver: bridge
