apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - adservice.yaml
 - cartservice.yaml
 - checkoutservice.yaml
 - currencyservice.yaml
 - emailservice.yaml
 - frontend.yaml
# - loadgenerator.yaml # During development, the loadgenerator module inside skaffold.yaml will be used.
 - paymentservice.yaml
 - productcatalogservice.yaml
 - recommendationservice.yaml
 - shippingservice.yaml
# components:
# - ../kustomize/components/cymbal-branding
# - ../kustomize/components/network-policies
# Platform-independent: Cloud-specific components are not needed
# - ../kustomize/components/memorystore
# - ../kustomize/components/alloydb
# - ../kustomize/components/shopping-assistant
# - ../kustomize/components/spanner
# - ../kustomize/components/container-images-tag
# - ../kustomize/components/container-images-tag-suffix
# - ../kustomize/components/container-images-registry
